export const FILE_TYPES = ['JPG', 'PNG', 'JPEG'];

export const FIRESTORE_IMG_BASE_START_URL =
  process.env.NEXT_PUBLIC_FIRESTORE_IMG_BASE_START_URL;

export const NEXT_PUBLIC_FIREBASE_API_KEY =
  process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
export const NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN =
  process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
export const NEXT_PUBLIC_FIREBASE_PROJECT_ID =
  process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
export const NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET =
  process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;
export const NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID =
  process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
export const NEXT_PUBLIC_FIREBASE_APP_ID =
  process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
export const DATABASE_URL = process.env.DATABASE_URL;
export const FIREBASE_SERVICE_ACCOUNT_KEY =
  process.env.FIREBASE_SERVICE_ACCOUNT_KEY;
export const SMTP_HOST = process.env.SMTP_HOST;
export const SMTP_PORT = +process.env.SMTP_PORT!;
export const SMTP_EMAIL = process.env.SMTP_EMAIL;
export const SMTP_PASSWORD = process.env.SMTP_PASSWORD;
