import { TimezoneOptions } from '@/interface/user';

export const timeZoneOptions: TimezoneOptions[] = [
  { label: 'Africa/Abidjan', value: 'Africa/Abidjan', offset: 0 },
  { label: 'Africa/Accra', value: 'Africa/Accra', offset: 0 },
  {
    label: 'Africa/Addis_Ababa',
    value: 'Africa/Addis_Ababa',
    offset: 10800000,
  },
  { label: 'Africa/Algiers', value: 'Africa/Algiers', offset: 3600000 },
  { label: 'Africa/Asmara', value: 'Africa/Asmara', offset: 10800000 },
  { label: 'Africa/Asmera', value: 'Africa/Asmera', offset: 10800000 },
  { label: 'Africa/Bamako', value: 'Africa/Bamako', offset: 0 },
  { label: 'Africa/Bangui', value: 'Africa/Bangui', offset: 3600000 },
  { label: 'Africa/Banjul', value: 'Africa/Banjul', offset: 0 },
  { label: 'Africa/Bissau', value: 'Africa/Bissau', offset: 0 },
  { label: 'Africa/Blantyre', value: 'Africa/Blantyre', offset: 7200000 },
  { label: 'Africa/Brazzaville', value: 'Africa/Brazzaville', offset: 3600000 },
  { label: 'Africa/Bujumbura', value: 'Africa/Bujumbura', offset: 7200000 },
  { label: 'Africa/Cairo', value: 'Africa/Cairo', offset: 7200000 },
  { label: 'Africa/Casablanca', value: 'Africa/Casablanca', offset: 0 },
  { label: 'Africa/Ceuta', value: 'Africa/Ceuta', offset: 7200000 },
  { label: 'Africa/Conakry', value: 'Africa/Conakry', offset: 0 },
  { label: 'Africa/Dakar', value: 'Africa/Dakar', offset: 0 },
  {
    label: 'Africa/Dar_es_Salaam',
    value: 'Africa/Dar_es_Salaam',
    offset: 10800000,
  },
  { label: 'Africa/Djibouti', value: 'Africa/Djibouti', offset: 10800000 },
  { label: 'Africa/Douala', value: 'Africa/Douala', offset: 3600000 },
  { label: 'Africa/El_Aaiun', value: 'Africa/El_Aaiun', offset: 0 },
  { label: 'Africa/Freetown', value: 'Africa/Freetown', offset: 0 },
  { label: 'Africa/Gaborone', value: 'Africa/Gaborone', offset: 7200000 },
  { label: 'Africa/Harare', value: 'Africa/Harare', offset: 7200000 },
  {
    label: 'Africa/Johannesburg',
    value: 'Africa/Johannesburg',
    offset: 7200000,
  },
  { label: 'Africa/Juba', value: 'Africa/Juba', offset: 10800000 },
  { label: 'Africa/Kampala', value: 'Africa/Kampala', offset: 10800000 },
  { label: 'Africa/Khartoum', value: 'Africa/Khartoum', offset: 10800000 },
  { label: 'Africa/Kigali', value: 'Africa/Kigali', offset: 7200000 },
  { label: 'Africa/Kinshasa', value: 'Africa/Kinshasa', offset: 3600000 },
  { label: 'Africa/Lagos', value: 'Africa/Lagos', offset: 3600000 },
  { label: 'Africa/Libreville', value: 'Africa/Libreville', offset: 3600000 },
  { label: 'Africa/Lome', value: 'Africa/Lome', offset: 0 },
  { label: 'Africa/Luanda', value: 'Africa/Luanda', offset: 3600000 },
  { label: 'Africa/Lubumbashi', value: 'Africa/Lubumbashi', offset: 7200000 },
  { label: 'Africa/Lusaka', value: 'Africa/Lusaka', offset: 7200000 },
  { label: 'Africa/Malabo', value: 'Africa/Malabo', offset: 3600000 },
  { label: 'Africa/Maputo', value: 'Africa/Maputo', offset: 7200000 },
  { label: 'Africa/Maseru', value: 'Africa/Maseru', offset: 7200000 },
  { label: 'Africa/Mbabane', value: 'Africa/Mbabane', offset: 7200000 },
  { label: 'Africa/Mogadishu', value: 'Africa/Mogadishu', offset: 10800000 },
  { label: 'Africa/Monrovia', value: 'Africa/Monrovia', offset: 0 },
  { label: 'Africa/Nairobi', value: 'Africa/Nairobi', offset: 10800000 },
  { label: 'Africa/Ndjamena', value: 'Africa/Ndjamena', offset: 3600000 },
  { label: 'Africa/Niamey', value: 'Africa/Niamey', offset: 3600000 },
  { label: 'Africa/Nouakchott', value: 'Africa/Nouakchott', offset: 0 },
  { label: 'Africa/Ouagadougou', value: 'Africa/Ouagadougou', offset: 0 },
  { label: 'Africa/Porto-Novo', value: 'Africa/Porto-Novo', offset: 3600000 },
  { label: 'Africa/Sao_Tome', value: 'Africa/Sao_Tome', offset: 0 },
  { label: 'Africa/Timbuktu', value: 'Africa/Timbuktu', offset: 0 },
  { label: 'Africa/Tripoli', value: 'Africa/Tripoli', offset: 7200000 },
  { label: 'Africa/Tunis', value: 'Africa/Tunis', offset: 3600000 },
  { label: 'Africa/Windhoek', value: 'Africa/Windhoek', offset: 7200000 },
  { label: 'America/Adak', value: 'America/Adak', offset: -32400000 },
  { label: 'America/Anchorage', value: 'America/Anchorage', offset: -28800000 },
  { label: 'America/Anguilla', value: 'America/Anguilla', offset: -14400000 },
  { label: 'America/Antigua', value: 'America/Antigua', offset: -14400000 },
  { label: 'America/Araguaina', value: 'America/Araguaina', offset: -10800000 },
  {
    label: 'America/Argentina/Buenos_Aires',
    offset: -10800000,
    value: 'America/Argentina/Buenos_Aires',
  },
  {
    label: 'America/Argentina/Catamarca',
    offset: -10800000,
    value: 'America/Argentina/Catamarca',
  },
  {
    label: 'America/Argentina/ComodRivadavia',
    offset: -10800000,
    value: 'America/Argentina/ComodRivadavia',
  },
  {
    label: 'America/Argentina/Cordoba',
    offset: -10800000,
    value: 'America/Argentina/Cordoba',
  },
  {
    label: 'America/Argentina/Jujuy',
    offset: -10800000,
    value: 'America/Argentina/Jujuy',
  },
  {
    label: 'America/Argentina/La_Rioja',
    offset: -10800000,
    value: 'America/Argentina/La_Rioja',
  },
  {
    label: 'America/Argentina/Mendoza',
    offset: -10800000,
    value: 'America/Argentina/Mendoza',
  },
  {
    label: 'America/Argentina/Rio_Gallegos',
    offset: -10800000,
    value: 'America/Argentina/Rio_Gallegos',
  },
  {
    label: 'America/Argentina/Salta',
    offset: -10800000,
    value: 'America/Argentina/Salta',
  },
  {
    label: 'America/Argentina/San_Juan',
    offset: -10800000,
    value: 'America/Argentina/San_Juan',
  },
  {
    label: 'America/Argentina/San_Luis',
    offset: -10800000,
    value: 'America/Argentina/San_Luis',
  },
  {
    label: 'America/Argentina/Tucuman',
    offset: -10800000,
    value: 'America/Argentina/Tucuman',
  },
  {
    label: 'America/Argentina/Ushuaia',
    offset: -10800000,
    value: 'America/Argentina/Ushuaia',
  },
  { label: 'America/Aruba', offset: -14400000, value: 'America/Aruba' },
  { label: 'America/Asuncion', offset: -14400000, value: 'America/Asuncion' },
  { label: 'America/Atikokan', offset: -18000000, value: 'America/Atikokan' },
  { label: 'America/Atka', offset: -32400000, value: 'America/Atka' },
  { label: 'America/Bahia', offset: -10800000, value: 'America/Bahia' },
  {
    label: 'America/Bahia_Banderas',
    offset: -18000000,
    value: 'America/Bahia_Banderas',
  },
  { label: 'America/Barbados', offset: -14400000, value: 'America/Barbados' },
  { label: 'America/Belem', offset: -10800000, value: 'America/Belem' },
  { label: 'America/Belize', offset: -21600000, value: 'America/Belize' },
  {
    label: 'America/Blanc-Sablon',
    offset: -14400000,
    value: 'America/Blanc-Sablon',
  },
  { label: 'America/Boa_Vista', offset: -14400000, value: 'America/Boa_Vista' },
  { label: 'America/Bogota', offset: -18000000, value: 'America/Bogota' },
  { label: 'America/Boise', offset: -21600000, value: 'America/Boise' },
  {
    label: 'America/Buenos_Aires',
    offset: -10800000,
    value: 'America/Buenos_Aires',
  },
  {
    label: 'America/Cambridge_Bay',
    offset: -21600000,
    value: 'America/Cambridge_Bay',
  },
  {
    label: 'America/Campo_Grande',
    offset: -14400000,
    value: 'America/Campo_Grande',
  },
  { label: 'America/Cancun', offset: -18000000, value: 'America/Cancun' },
  { label: 'America/Caracas', offset: -14400000, value: 'America/Caracas' },
  { label: 'America/Catamarca', offset: -10800000, value: 'America/Catamarca' },
  { label: 'America/Cayenne', offset: -10800000, value: 'America/Cayenne' },
  { label: 'America/Cayman', offset: -18000000, value: 'America/Cayman' },
  { label: 'America/Chicago', offset: -18000000, value: 'America/Chicago' },
  { label: 'America/Chihuahua', offset: -21600000, value: 'America/Chihuahua' },
  {
    label: 'America/Coral_Harbour',
    offset: -18000000,
    value: 'America/Coral_Harbour',
  },
  { label: 'America/Cordoba', offset: -10800000, value: 'America/Cordoba' },
  {
    label: 'America/Costa_Rica',
    offset: -21600000,
    value: 'America/Costa_Rica',
  },
  { label: 'America/Creston', offset: -25200000, value: 'America/Creston' },
  { label: 'America/Cuiaba', offset: -14400000, value: 'America/Cuiaba' },
  { label: 'America/Curacao', offset: -14400000, value: 'America/Curacao' },
  { label: 'America/Danmarkshavn', offset: 0, value: 'America/Danmarkshavn' },
  { label: 'America/Dawson', offset: -25200000, value: 'America/Dawson' },
  {
    label: 'America/Dawson_Creek',
    offset: -25200000,
    value: 'America/Dawson_Creek',
  },
  { label: 'America/Denver', offset: -21600000, value: 'America/Denver' },
  { label: 'America/Detroit', offset: -14400000, value: 'America/Detroit' },
  { label: 'America/Dominica', offset: -14400000, value: 'America/Dominica' },
  { label: 'America/Edmonton', offset: -21600000, value: 'America/Edmonton' },
  { label: 'America/Eirunepe', offset: -18000000, value: 'America/Eirunepe' },
  {
    label: 'America/El_Salvador',
    offset: -21600000,
    value: 'America/El_Salvador',
  },
  { label: 'America/Ensenada', offset: -25200000, value: 'America/Ensenada' },
  {
    label: 'America/Fort_Nelson',
    offset: -25200000,
    value: 'America/Fort_Nelson',
  },
  {
    label: 'America/Fort_Wayne',
    offset: -14400000,
    value: 'America/Fort_Wayne',
  },
  { label: 'America/Fortaleza', offset: -10800000, value: 'America/Fortaleza' },
  { label: 'America/Glace_Bay', offset: -10800000, value: 'America/Glace_Bay' },
  { label: 'America/Godthab', offset: -7200000, value: 'America/Godthab' },
  { label: 'America/Goose_Bay', offset: -10800000, value: 'America/Goose_Bay' },
  {
    label: 'America/Grand_Turk',
    offset: -14400000,
    value: 'America/Grand_Turk',
  },
  { label: 'America/Grenada', offset: -14400000, value: 'America/Grenada' },
  {
    label: 'America/Guadeloupe',
    offset: -14400000,
    value: 'America/Guadeloupe',
  },
  { label: 'America/Guatemala', offset: -21600000, value: 'America/Guatemala' },
  { label: 'America/Guayaquil', offset: -18000000, value: 'America/Guayaquil' },
  { label: 'America/Guyana', offset: -14400000, value: 'America/Guyana' },
  { label: 'America/Halifax', offset: -10800000, value: 'America/Halifax' },
  { label: 'America/Havana', offset: -14400000, value: 'America/Havana' },
  {
    label: 'America/Hermosillo',
    offset: -25200000,
    value: 'America/Hermosillo',
  },
  {
    label: 'America/Indiana/Indianapolis',
    offset: -14400000,
    value: 'America/Indiana/Indianapolis',
  },
  {
    label: 'America/Indiana/Knox',
    offset: -18000000,
    value: 'America/Indiana/Knox',
  },
  {
    label: 'America/Indiana/Marengo',
    offset: -14400000,
    value: 'America/Indiana/Marengo',
  },
  {
    label: 'America/Indiana/Petersburg',
    offset: -14400000,
    value: 'America/Indiana/Petersburg',
  },
  {
    label: 'America/Indiana/Tell_City',
    offset: -18000000,
    value: 'America/Indiana/Tell_City',
  },
  {
    label: 'America/Indiana/Vevay',
    offset: -14400000,
    value: 'America/Indiana/Vevay',
  },
  {
    label: 'America/Indiana/Vincennes',
    offset: -14400000,
    value: 'America/Indiana/Vincennes',
  },
  {
    label: 'America/Indiana/Winamac',
    offset: -14400000,
    value: 'America/Indiana/Winamac',
  },
  {
    label: 'America/Indianapolis',
    offset: -14400000,
    value: 'America/Indianapolis',
  },
  { label: 'America/Inuvik', offset: -21600000, value: 'America/Inuvik' },
  { label: 'America/Iqaluit', offset: -14400000, value: 'America/Iqaluit' },
  { label: 'America/Jamaica', offset: -18000000, value: 'America/Jamaica' },
  { label: 'America/Jujuy', offset: -10800000, value: 'America/Jujuy' },
  { label: 'America/Juneau', offset: -28800000, value: 'America/Juneau' },
  {
    label: 'America/Kentucky/Louisville',
    offset: -14400000,
    value: 'America/Kentucky/Louisville',
  },
  {
    label: 'America/Kentucky/Monticello',
    offset: -14400000,
    value: 'America/Kentucky/Monticello',
  },
  { label: 'America/Knox_IN', offset: -18000000, value: 'America/Knox_IN' },
  {
    label: 'America/Kralendijk',
    offset: -14400000,
    value: 'America/Kralendijk',
  },
  { label: 'America/La_Paz', offset: -14400000, value: 'America/La_Paz' },
  { label: 'America/Lima', offset: -18000000, value: 'America/Lima' },
  {
    label: 'America/Los_Angeles',
    offset: -25200000,
    value: 'America/Los_Angeles',
  },
  {
    label: 'America/Louisville',
    offset: -14400000,
    value: 'America/Louisville',
  },
  {
    label: 'America/Lower_Princes',
    offset: -14400000,
    value: 'America/Lower_Princes',
  },
  { label: 'America/Maceio', offset: -10800000, value: 'America/Maceio' },
  { label: 'America/Managua', offset: -21600000, value: 'America/Managua' },
  { label: 'America/Manaus', offset: -14400000, value: 'America/Manaus' },
  { label: 'America/Marigot', offset: -14400000, value: 'America/Marigot' },
  {
    label: 'America/Martinique',
    offset: -14400000,
    value: 'America/Martinique',
  },
  { label: 'America/Matamoros', offset: -21600000, value: 'America/Matamoros' },
  { label: 'America/Mazatlan', offset: -25200000, value: 'America/Mazatlan' },
  { label: 'America/Mendoza', offset: -10800000, value: 'America/Mendoza' },
  { label: 'America/Menominee', offset: -18000000, value: 'America/Menominee' },
  { label: 'America/Merida', offset: -21600000, value: 'America/Merida' },
  {
    label: 'America/Metlakatla',
    offset: -28800000,
    value: 'America/Metlakatla',
  },
  {
    label: 'America/Mexico_City',
    offset: -21600000,
    value: 'America/Mexico_City',
  },
  { label: 'America/Miquelon', offset: -7200000, value: 'America/Miquelon' },
  { label: 'America/Moncton', offset: -10800000, value: 'America/Moncton' },
  { label: 'America/Monterrey', offset: -21600000, value: 'America/Monterrey' },
  {
    label: 'America/Montevideo',
    offset: -10800000,
    value: 'America/Montevideo',
  },
  { label: 'America/Montreal', offset: -14400000, value: 'America/Montreal' },
  {
    label: 'America/Montserrat',
    offset: -14400000,
    value: 'America/Montserrat',
  },
  { label: 'America/Nassau', offset: -14400000, value: 'America/Nassau' },
  { label: 'America/New_York', offset: -14400000, value: 'America/New_York' },
  { label: 'America/Nipigon', offset: -14400000, value: 'America/Nipigon' },
  { label: 'America/Nome', offset: -28800000, value: 'America/Nome' },
  { label: 'America/Noronha', offset: -7200000, value: 'America/Noronha' },
  {
    label: 'America/North_Dakota/Beulah',
    offset: -18000000,
    value: 'America/North_Dakota/Beulah',
  },
  {
    label: 'America/North_Dakota/Center',
    offset: -18000000,
    value: 'America/North_Dakota/Center',
  },
  {
    label: 'America/North_Dakota/New_Salem',
    offset: -18000000,
    value: 'America/North_Dakota/New_Salem',
  },
  { label: 'America/Nuuk', offset: -7200000, value: 'America/Nuuk' },
  { label: 'America/Ojinaga', offset: -21600000, value: 'America/Ojinaga' },
  { label: 'America/Panama', offset: -18000000, value: 'America/Panama' },
  {
    label: 'America/Pangnirtung',
    offset: -14400000,
    value: 'America/Pangnirtung',
  },
  {
    label: 'America/Paramaribo',
    offset: -10800000,
    value: 'America/Paramaribo',
  },
  { label: 'America/Phoenix', offset: -25200000, value: 'America/Phoenix' },
  {
    label: 'America/Port_of_Spain',
    offset: -14400000,
    value: 'America/Port_of_Spain',
  },
  {
    label: 'America/Port-au-Prince',
    offset: -14400000,
    value: 'America/Port-au-Prince',
  },
  {
    label: 'America/Porto_Acre',
    offset: -18000000,
    value: 'America/Porto_Acre',
  },
  {
    label: 'America/Porto_Velho',
    offset: -14400000,
    value: 'America/Porto_Velho',
  },
  {
    label: 'America/Puerto_Rico',
    offset: -14400000,
    value: 'America/Puerto_Rico',
  },
  {
    label: 'America/Punta_Arenas',
    offset: -10800000,
    value: 'America/Punta_Arenas',
  },
  {
    label: 'America/Rainy_River',
    offset: -18000000,
    value: 'America/Rainy_River',
  },
  {
    label: 'America/Rankin_Inlet',
    offset: -18000000,
    value: 'America/Rankin_Inlet',
  },
  { label: 'America/Recife', offset: -10800000, value: 'America/Recife' },
  { label: 'America/Regina', offset: -21600000, value: 'America/Regina' },
  { label: 'America/Resolute', offset: -18000000, value: 'America/Resolute' },
  {
    label: 'America/Rio_Branco',
    offset: -18000000,
    value: 'America/Rio_Branco',
  },
  { label: 'America/Rosario', offset: -10800000, value: 'America/Rosario' },
  {
    label: 'America/Santa_Isabel',
    offset: -28800000,
    value: 'America/Santa_Isabel',
  },
  { label: 'America/Santarem', offset: -10800000, value: 'America/Santarem' },
  { label: 'America/Santiago', offset: -10800000, value: 'America/Santiago' },
  {
    label: 'America/Santo_Domingo',
    offset: -14400000,
    value: 'America/Santo_Domingo',
  },
  { label: 'America/Sao_Paulo', offset: -10800000, value: 'America/Sao_Paulo' },
  {
    label: 'America/Scoresbysund',
    offset: -7200000,
    value: 'America/Scoresbysund',
  },
  { label: 'America/Shiprock', offset: -25200000, value: 'America/Shiprock' },
  { label: 'America/Sitka', offset: -28800000, value: 'America/Sitka' },
  {
    label: 'America/St_Barthelemy',
    offset: -14400000,
    value: 'America/St_Barthelemy',
  },
  { label: 'America/St_Johns', offset: -9000000, value: 'America/St_Johns' },
  { label: 'America/St_Kitts', offset: -14400000, value: 'America/St_Kitts' },
  { label: 'America/St_Lucia', offset: -14400000, value: 'America/St_Lucia' },
  { label: 'America/St_Thomas', offset: -14400000, value: 'America/St_Thomas' },
  {
    label: 'America/St_Vincent',
    offset: -14400000,
    value: 'America/St_Vincent',
  },
  {
    label: 'America/Swift_Current',
    offset: -21600000,
    value: 'America/Swift_Current',
  },
  {
    label: 'America/Tegucigalpa',
    offset: -21600000,
    value: 'America/Tegucigalpa',
  },
  { label: 'America/Thule', offset: -10800000, value: 'America/Thule' },
  {
    label: 'America/Thunder_Bay',
    offset: -14400000,
    value: 'America/Thunder_Bay',
  },
  { label: 'America/Tijuana', offset: -25200000, value: 'America/Tijuana' },
  { label: 'America/Toronto', offset: -14400000, value: 'America/Toronto' },
  { label: 'America/Tortola', offset: -14400000, value: 'America/Tortola' },
  { label: 'America/Vancouver', offset: -25200000, value: 'America/Vancouver' },
  { label: 'America/Virgin', offset: -14400000, value: 'America/Virgin' },
  {
    label: 'America/Whitehorse',
    offset: -25200000,
    value: 'America/Whitehorse',
  },
  { label: 'America/Winnipeg', offset: -18000000, value: 'America/Winnipeg' },
  { label: 'America/Yakutat', offset: -28800000, value: 'America/Yakutat' },
  {
    label: 'America/Yellowknife',
    offset: -21600000,
    value: 'America/Yellowknife',
  },
  { label: 'Antarctica/Casey', offset: 28800000, value: 'Antarctica/Casey' },
  { label: 'Antarctica/Davis', offset: 25200000, value: 'Antarctica/Davis' },
  {
    label: 'Antarctica/DumontDUrville',
    offset: 36000000,
    value: 'Antarctica/DumontDUrville',
  },
  {
    label: 'Antarctica/Macquarie',
    offset: 39600000,
    value: 'Antarctica/Macquarie',
  },
  { label: 'Antarctica/Mawson', offset: 18000000, value: 'Antarctica/Mawson' },
  {
    label: 'Antarctica/McMurdo',
    offset: 46800000,
    value: 'Antarctica/McMurdo',
  },
  { label: 'Antarctica/Palmer', offset: -10800000, value: 'Antarctica/Palmer' },
  {
    label: 'Antarctica/Rothera',
    offset: -10800000,
    value: 'Antarctica/Rothera',
  },
  {
    label: 'Antarctica/South_Pole',
    offset: 46800000,
    value: 'Antarctica/South_Pole',
  },
  { label: 'Antarctica/Syowa', offset: 10800000, value: 'Antarctica/Syowa' },
  { label: 'Antarctica/Troll', offset: 0, value: 'Antarctica/Troll' },
  { label: 'Antarctica/Vostok', offset: 21600000, value: 'Antarctica/Vostok' },
  {
    label: 'Arctic/Longyearbyen',
    offset: 7200000,
    value: 'Arctic/Longyearbyen',
  },
  { label: 'Asia/Aden', offset: 10800000, value: 'Asia/Aden' },
  { label: 'Asia/Almaty', offset: 21600000, value: 'Asia/Almaty' },
  { label: 'Asia/Amman', offset: 10800000, value: 'Asia/Amman' },
  { label: 'Asia/Anadyr', offset: 43200000, value: 'Asia/Anadyr' },
  { label: 'Asia/Aqtau', offset: 18000000, value: 'Asia/Aqtau' },
  { label: 'Asia/Aqtobe', offset: 18000000, value: 'Asia/Aqtobe' },
  { label: 'Asia/Ashgabat', offset: 18000000, value: 'Asia/Ashgabat' },
  { label: 'Asia/Ashkhabad', offset: 18000000, value: 'Asia/Ashkhabad' },
  { label: 'Asia/Atyrau', offset: 18000000, value: 'Asia/Atyrau' },
  { label: 'Asia/Baghdad', offset: 10800000, value: 'Asia/Baghdad' },
  { label: 'Asia/Bahrain', offset: 10800000, value: 'Asia/Bahrain' },
  { label: 'Asia/Baku', offset: 14400000, value: 'Asia/Baku' },
  { label: 'Asia/Bangkok', offset: 25200000, value: 'Asia/Bangkok' },
  { label: 'Asia/Barnaul', offset: 25200000, value: 'Asia/Barnaul' },
  { label: 'Asia/Beirut', offset: 10800000, value: 'Asia/Beirut' },
  { label: 'Asia/Bishkek', offset: 21600000, value: 'Asia/Bishkek' },
  { label: 'Asia/Brunei', offset: 28800000, value: 'Asia/Brunei' },
  { label: 'Asia/Calcutta', offset: 19800000, value: 'Asia/Calcutta' },
  { label: 'Asia/Chita', offset: 28800000, value: 'Asia/Chita' },
  { label: 'Asia/Choibalsan', offset: 28800000, value: 'Asia/Choibalsan' },
  { label: 'Asia/Chongqing', offset: 28800000, value: 'Asia/Chongqing' },
  { label: 'Asia/Chungking', offset: 28800000, value: 'Asia/Chungking' },
  { label: 'Asia/Colombo', offset: 19800000, value: 'Asia/Colombo' },
  { label: 'Asia/Dacca', offset: 21600000, value: 'Asia/Dacca' },
  { label: 'Asia/Damascus', offset: 10800000, value: 'Asia/Damascus' },
  { label: 'Asia/Dhaka', offset: 21600000, value: 'Asia/Dhaka' },
  { label: 'Asia/Dili', offset: 32400000, value: 'Asia/Dili' },
  { label: 'Asia/Dubai', offset: 14400000, value: 'Asia/Dubai' },
  { label: 'Asia/Dushanbe', offset: 18000000, value: 'Asia/Dushanbe' },
  { label: 'Asia/Famagusta', offset: 10800000, value: 'Asia/Famagusta' },
  { label: 'Asia/Gaza', offset: 10800000, value: 'Asia/Gaza' },
  { label: 'Asia/Harbin', offset: 28800000, value: 'Asia/Harbin' },
  { label: 'Asia/Hebron', offset: 10800000, value: 'Asia/Hebron' },
  { label: 'Asia/Ho_Chi_Minh', offset: 25200000, value: 'Asia/Ho_Chi_Minh' },
  { label: 'Asia/Hong_Kong', offset: 28800000, value: 'Asia/Hong_Kong' },
  { label: 'Asia/Hovd', offset: 25200000, value: 'Asia/Hovd' },
  { label: 'Asia/Irkutsk', offset: 28800000, value: 'Asia/Irkutsk' },
  { label: 'Asia/Istanbul', offset: 10800000, value: 'Asia/Istanbul' },
  { label: 'Asia/Jakarta', offset: 25200000, value: 'Asia/Jakarta' },
  { label: 'Asia/Jayapura', offset: 32400000, value: 'Asia/Jayapura' },
  { label: 'Asia/Jerusalem', offset: 10800000, value: 'Asia/Jerusalem' },
  { label: 'Asia/Kabul', offset: 16200000, value: 'Asia/Kabul' },
  { label: 'Asia/Kamchatka', offset: 43200000, value: 'Asia/Kamchatka' },
  { label: 'Asia/Karachi', offset: 18000000, value: 'Asia/Karachi' },
  { label: 'Asia/Kashgar', offset: 28800000, value: 'Asia/Kashgar' },
  { label: 'Asia/Kathmandu', offset: 20700000, value: 'Asia/Kathmandu' },
  { label: 'Asia/Katmandu', offset: 20700000, value: 'Asia/Katmandu' },
  { label: 'Asia/Khandyga', offset: 32400000, value: 'Asia/Khandyga' },
  { label: 'Asia/Kolkata', offset: 19800000, value: 'Asia/Kolkata' },
  { label: 'Asia/Krasnoyarsk', offset: 25200000, value: 'Asia/Krasnoyarsk' },
  { label: 'Asia/Kuala_Lumpur', offset: 28800000, value: 'Asia/Kuala_Lumpur' },
  { label: 'Asia/Kuching', offset: 28800000, value: 'Asia/Kuching' },
  { label: 'Asia/Kuwait', offset: 10800000, value: 'Asia/Kuwait' },
  { label: 'Asia/Macao', offset: 28800000, value: 'Asia/Macao' },
  { label: 'Asia/Macau', offset: 28800000, value: 'Asia/Macau' },
  { label: 'Asia/Magadan', offset: 39600000, value: 'Asia/Magadan' },
  { label: 'Asia/Makassar', offset: 28800000, value: 'Asia/Makassar' },
  { label: 'Asia/Manila', offset: 28800000, value: 'Asia/Manila' },
  { label: 'Asia/Muscat', offset: 14400000, value: 'Asia/Muscat' },
  { label: 'Asia/Nicosia', offset: 10800000, value: 'Asia/Nicosia' },
  { label: 'Asia/Novokuznetsk', offset: 25200000, value: 'Asia/Novokuznetsk' },
  { label: 'Asia/Novosibirsk', offset: 25200000, value: 'Asia/Novosibirsk' },
  { label: 'Asia/Omsk', offset: 21600000, value: 'Asia/Omsk' },
  { label: 'Asia/Oral', offset: 18000000, value: 'Asia/Oral' },
  { label: 'Asia/Phnom_Penh', offset: 25200000, value: 'Asia/Phnom_Penh' },
  { label: 'Asia/Pontianak', offset: 25200000, value: 'Asia/Pontianak' },
  { label: 'Asia/Pyongyang', offset: 28800000, value: 'Asia/Pyongyang' },
  { label: 'Asia/Qatar', offset: 10800000, value: 'Asia/Qatar' },
  { label: 'Asia/Qostanay', offset: 21600000, value: 'Asia/Qostanay' },
  { label: 'Asia/Qyzylorda', offset: 21600000, value: 'Asia/Qyzylorda' },
  { label: 'Asia/Rangoon', offset: 23400000, value: 'Asia/Rangoon' },
  { label: 'Asia/Riyadh', offset: 10800000, value: 'Asia/Riyadh' },
  { label: 'Asia/Saigon', offset: 25200000, value: 'Asia/Saigon' },
  { label: 'Asia/Sakhalin', offset: 39600000, value: 'Asia/Sakhalin' },
  { label: 'Asia/Samarkand', offset: 18000000, value: 'Asia/Samarkand' },
  { label: 'Asia/Seoul', offset: 32400000, value: 'Asia/Seoul' },
  { label: 'Asia/Shanghai', offset: 28800000, value: 'Asia/Shanghai' },
  { label: 'Asia/Singapore', offset: 28800000, value: 'Asia/Singapore' },
  {
    label: 'Asia/Srednekolymsk',
    offset: 39600000,
    value: 'Asia/Srednekolymsk',
  },
  { label: 'Asia/Taipei', offset: 28800000, value: 'Asia/Taipei' },
  { label: 'Asia/Tashkent', offset: 18000000, value: 'Asia/Tashkent' },
  { label: 'Asia/Tbilisi', offset: 14400000, value: 'Asia/Tbilisi' },
  { label: 'Asia/Tehran', offset: 16200000, value: 'Asia/Tehran' },
  { label: 'Asia/Tel_Aviv', offset: 10800000, value: 'Asia/Tel_Aviv' },
  { label: 'Asia/Thimbu', offset: 21600000, value: 'Asia/Thimbu' },
  { label: 'Asia/Thimphu', offset: 21600000, value: 'Asia/Thimphu' },
  { label: 'Asia/Tokyo', offset: 32400000, value: 'Asia/Tokyo' },
  { label: 'Asia/Tomsk', offset: 25200000, value: 'Asia/Tomsk' },
  {
    label: 'Asia/Ujung_Pandang',
    offset: 28800000,
    value: 'Asia/Ujung_Pandang',
  },
  { label: 'Asia/Ulaanbaatar', offset: 28800000, value: 'Asia/Ulaanbaatar' },
  { label: 'Asia/Ulan_Bator', offset: 28800000, value: 'Asia/Ulan_Bator' },
  { label: 'Asia/Urumqi', offset: 28800000, value: 'Asia/Urumqi' },
  { label: 'Asia/Ust-Nera', offset: 36000000, value: 'Asia/Ust-Nera' },
  { label: 'Asia/Vientiane', offset: 25200000, value: 'Asia/Vientiane' },
  { label: 'Asia/Vladivostok', offset: 39600000, value: 'Asia/Vladivostok' },
  { label: 'Asia/Yakutsk', offset: 32400000, value: 'Asia/Yakutsk' },
  { label: 'Asia/Yangon', offset: 23400000, value: 'Asia/Yangon' },
  {
    label: 'Asia/Yekaterinburg',
    offset: 18000000,
    value: 'Asia/Yekaterinburg',
  },
  { label: 'Asia/Yerevan', offset: 14400000, value: 'Asia/Yerevan' },
  { label: 'Atlantic/Azores', offset: -3600000, value: 'Atlantic/Azores' },
  { label: 'Atlantic/Bermuda', offset: -10800000, value: 'Atlantic/Bermuda' },
  { label: 'Atlantic/Canary', offset: 0, value: 'Atlantic/Canary' },
  {
    label: 'Atlantic/Cape_Verde',
    offset: -3600000,
    value: 'Atlantic/Cape_Verde',
  },
  { label: 'Atlantic/Faeroe', offset: 0, value: 'Atlantic/Faeroe' },
  { label: 'Atlantic/Faroe', offset: 0, value: 'Atlantic/Faroe' },
  { label: 'Atlantic/Jan_Mayen', offset: 0, value: 'Atlantic/Jan_Mayen' },
  { label: 'Atlantic/Madeira', offset: 0, value: 'Atlantic/Madeira' },
  { label: 'Atlantic/Reykjavik', offset: 0, value: 'Atlantic/Reykjavik' },
  {
    label: 'Atlantic/South_Georgia',
    offset: -7200000,
    value: 'Atlantic/South_Georgia',
  },
  { label: 'Atlantic/St_Helena', offset: 0, value: 'Atlantic/St_Helena' },
  { label: 'Atlantic/Stanley', offset: -10800000, value: 'Atlantic/Stanley' },
  { label: 'Australia/ACT', offset: 36000000, value: 'Australia/ACT' },
  {
    label: 'Australia/Adelaide',
    offset: 34200000,
    value: 'Australia/Adelaide',
  },
  {
    label: 'Australia/Brisbane',
    offset: 36000000,
    value: 'Australia/Brisbane',
  },
  {
    label: 'Australia/Broken_Hill',
    offset: 34200000,
    value: 'Australia/Broken_Hill',
  },
  {
    label: 'Australia/Canberra',
    offset: 36000000,
    value: 'Australia/Canberra',
  },
  { label: 'Australia/Currie', offset: 36000000, value: 'Australia/Currie' },
  { label: 'Australia/Darwin', offset: 34200000, value: 'Australia/Darwin' },
  { label: 'Australia/Eucla', offset: 31500000, value: 'Australia/Eucla' },
  { label: 'Australia/Hobart', offset: 36000000, value: 'Australia/Hobart' },
  { label: 'Australia/LHI', offset: 37800000, value: 'Australia/LHI' },
  {
    label: 'Australia/Lindeman',
    offset: 36000000,
    value: 'Australia/Lindeman',
  },
  {
    label: 'Australia/Lord_Howe',
    offset: 37800000,
    value: 'Australia/Lord_Howe',
  },
  {
    label: 'Australia/Melbourne',
    offset: 36000000,
    value: 'Australia/Melbourne',
  },
  { label: 'Australia/North', offset: 34200000, value: 'Australia/North' },
  { label: 'Australia/NSW', offset: 36000000, value: 'Australia/NSW' },
  { label: 'Australia/Perth', offset: 28800000, value: 'Australia/Perth' },
  {
    label: 'Australia/Queensland',
    offset: 36000000,
    value: 'Australia/Queensland',
  },
  { label: 'Australia/South', offset: 34200000, value: 'Australia/South' },
  { label: 'Australia/Sydney', offset: 36000000, value: 'Australia/Sydney' },
  {
    label: 'Australia/Tasmania',
    offset: 36000000,
    value: 'Australia/Tasmania',
  },
  {
    label: 'Australia/Victoria',
    offset: 36000000,
    value: 'Australia/Victoria',
  },
  { label: 'Australia/West', offset: 28800000, value: 'Australia/West' },
  {
    label: 'Australia/Yancowinna',
    offset: 34200000,
    value: 'Australia/Yancowinna',
  },
  { label: 'Brazil/Acre', offset: -18000000, value: 'Brazil/Acre' },
  { label: 'Brazil/DeNoronha', offset: -7200000, value: 'Brazil/DeNoronha' },
  { label: 'Brazil/East', offset: -10800000, value: 'Brazil/East' },
  { label: 'Brazil/West', offset: -14400000, value: 'Brazil/West' },
  { label: 'Canada/Atlantic', offset: -10800000, value: 'Canada/Atlantic' },
  { label: 'Canada/Central', offset: -18000000, value: 'Canada/Central' },
  { label: 'Canada/Eastern', offset: -14400000, value: 'Canada/Eastern' },
  { label: 'Canada/Mountain', offset: -21600000, value: 'Canada/Mountain' },
  {
    label: 'Canada/Newfoundland',
    offset: -12600000,
    value: 'Canada/Newfoundland',
  },
  { label: 'Canada/Pacific', offset: -25200000, value: 'Canada/Pacific' },
  {
    label: 'Canada/Saskatchewan',
    offset: -21600000,
    value: 'Canada/Saskatchewan',
  },
  { label: 'Canada/Yukon', offset: -25200000, value: 'Canada/Yukon' },
  { label: 'CET', offset: 3600000, value: 'CET' },
  { label: 'Chile/Continental', offset: -10800000, value: 'Chile/Continental' },
  {
    label: 'Chile/EasterIsland',
    offset: -18000000,
    value: 'Chile/EasterIsland',
  },
  { label: 'CST6CDT', offset: -21600000, value: 'CST6CDT' },
  { label: 'Cuba', offset: -14400000, value: 'Cuba' },
  { label: 'EET', offset: 7200000, value: 'EET' },
  { label: 'Egypt', offset: 7200000, value: 'Egypt' },
  { label: 'Eire', offset: 0, value: 'Eire' },
  { label: 'EST', offset: -18000000, value: 'EST' },
  { label: 'EST5EDT', offset: -18000000, value: 'EST5EDT' },
  { label: 'Etc/GMT', offset: 0, value: 'Etc/GMT' },
  { label: 'Etc/GMT-0', offset: 0, value: 'Etc/GMT-0' },
  { label: 'Etc/GMT-1', offset: -3600000, value: 'Etc/GMT-1' },
  { label: 'Etc/GMT-10', offset: -36000000, value: 'Etc/GMT-10' },
  { label: 'Etc/GMT-11', offset: -39600000, value: 'Etc/GMT-11' },
  { label: 'Etc/GMT-12', offset: -43200000, value: 'Etc/GMT-12' },
  { label: 'Etc/GMT-13', offset: -46800000, value: 'Etc/GMT-13' },
  { label: 'Etc/GMT-14', offset: -50400000, value: 'Etc/GMT-14' },

  { label: 'Etc/GMT-2', offset: -7200000, value: 'Etc/GMT-2' },
  { label: 'Etc/GMT-3', offset: -10800000, value: 'Etc/GMT-3' },
  { label: 'Etc/GMT-4', offset: -14400000, value: 'Etc/GMT-4' },
  { label: 'Etc/GMT-5', offset: -18000000, value: 'Etc/GMT-5' },
  { label: 'Etc/GMT-6', offset: -21600000, value: 'Etc/GMT-6' },
  { label: 'Etc/GMT-7', offset: -25200000, value: 'Etc/GMT-7' },
  { label: 'Etc/GMT-8', offset: -28800000, value: 'Etc/GMT-8' },
  { label: 'Etc/GMT-9', offset: -32400000, value: 'Etc/GMT-9' },
  { label: 'Etc/GMT+0', offset: 0, value: 'Etc/GMT+0' },
  { label: 'Etc/GMT+1', offset: 3600000, value: 'Etc/GMT+1' },
  { label: 'Etc/GMT+10', offset: 36000000, value: 'Etc/GMT+10' },
  { label: 'Etc/GMT+11', offset: 39600000, value: 'Etc/GMT+11' },
  { label: 'Etc/GMT+12', offset: 43200000, value: 'Etc/GMT+12' },
  { label: 'Etc/GMT+2', offset: 7200000, value: 'Etc/GMT+2' },
  { label: 'Etc/GMT+3', offset: 10800000, value: 'Etc/GMT+3' },
  { label: 'Etc/GMT+4', offset: 14400000, value: 'Etc/GMT+4' },
  { label: 'Etc/GMT+5', offset: 18000000, value: 'Etc/GMT+5' },
  { label: 'Etc/GMT+6', offset: 21600000, value: 'Etc/GMT+6' },
  { label: 'Etc/GMT+7', offset: 25200000, value: 'Etc/GMT+7' },
  { label: 'Etc/GMT+8', offset: 28800000, value: 'Etc/GMT+8' },
  { label: 'Etc/GMT+9', offset: 32400000, value: 'Etc/GMT+9' },
  { label: 'Etc/GMT0', offset: 0, value: 'Etc/GMT0' },
  { label: 'Etc/Greenwich', offset: 0, value: 'Etc/Greenwich' },
  { label: 'Etc/UCT', offset: 0, value: 'Etc/UCT' },
  { label: 'Etc/Universal', offset: 0, value: 'Etc/Universal' },
  { label: 'Etc/UTC', offset: 0, value: 'Etc/UTC' },
  { label: 'Etc/Zulu', offset: 0, value: 'Etc/Zulu' },
  { label: 'Europe/Amsterdam', offset: 3600000, value: 'Europe/Amsterdam' },
  { label: 'Europe/Andorra', offset: 3600000, value: 'Europe/Andorra' },
  { label: 'Europe/Astrakhan', offset: 14400000, value: 'Europe/Astrakhan' },
  { label: 'Europe/Athens', offset: 10800000, value: 'Europe/Athens' },
  { label: 'Europe/Belfast', offset: 0, value: 'Europe/Belfast' },
  { label: 'Europe/Belgrade', offset: 3600000, value: 'Europe/Belgrade' },
  { label: 'Europe/Berlin', offset: 3600000, value: 'Europe/Berlin' },
  { label: 'Europe/Bratislava', offset: 3600000, value: 'Europe/Bratislava' },
  { label: 'Europe/Brussels', offset: 3600000, value: 'Europe/Brussels' },
  { label: 'Europe/Bucharest', offset: 10800000, value: 'Europe/Bucharest' },
  { label: 'Europe/Budapest', offset: 3600000, value: 'Europe/Budapest' },
  { label: 'Europe/Busingen', offset: 3600000, value: 'Europe/Busingen' },
  { label: 'Europe/Chisinau', offset: 10800000, value: 'Europe/Chisinau' },
  { label: 'Europe/Copenhagen', offset: 3600000, value: 'Europe/Copenhagen' },
  { label: 'Europe/Dublin', offset: 0, value: 'Europe/Dublin' },
  { label: 'Europe/Gibraltar', offset: 3600000, value: 'Europe/Gibraltar' },
  { label: 'Europe/Guernsey', offset: 0, value: 'Europe/Guernsey' },
  { label: 'Europe/Helsinki', offset: 10800000, value: 'Europe/Helsinki' },
  { label: 'Europe/Isle_of_Man', offset: 0, value: 'Europe/Isle_of_Man' },
  { label: 'Europe/Istanbul', offset: 10800000, value: 'Europe/Istanbul' },
  { label: 'Europe/Jersey', offset: 0, value: 'Europe/Jersey' },
  { label: 'Europe/Kaliningrad', offset: 7200000, value: 'Europe/Kaliningrad' },
  { label: 'Europe/Kiev', offset: 10800000, value: 'Europe/Kiev' },
  { label: 'Europe/Kirov', offset: 10800000, value: 'Europe/Kirov' },
  { label: 'Europe/Kyiv', offset: 10800000, value: 'Europe/Kyiv' },
  { label: 'Europe/Lisbon', offset: 0, value: 'Europe/Lisbon' },
  { label: 'Europe/Ljubljana', offset: 3600000, value: 'Europe/Ljubljana' },
  { label: 'Europe/London', offset: 0, value: 'Europe/London' },
  { label: 'Europe/Luxembourg', offset: 3600000, value: 'Europe/Luxembourg' },
  { label: 'Europe/Madrid', offset: 3600000, value: 'Europe/Madrid' },
  { label: 'Europe/Malta', offset: 3600000, value: 'Europe/Malta' },
  { label: 'Europe/Mariehamn', offset: 10800000, value: 'Europe/Mariehamn' },
  { label: 'Europe/Minsk', offset: 10800000, value: 'Europe/Minsk' },
  { label: 'Europe/Monaco', offset: 3600000, value: 'Europe/Monaco' },
  { label: 'Europe/Moscow', offset: 10800000, value: 'Europe/Moscow' },
  { label: 'Europe/Nicosia', offset: 10800000, value: 'Europe/Nicosia' },
  { label: 'Europe/Oslo', offset: 3600000, value: 'Europe/Oslo' },
  { label: 'Europe/Paris', offset: 3600000, value: 'Europe/Paris' },
  { label: 'Europe/Podgorica', offset: 3600000, value: 'Europe/Podgorica' },
  { label: 'Europe/Prague', offset: 3600000, value: 'Europe/Prague' },
  { label: 'Europe/Riga', offset: 10800000, value: 'Europe/Riga' },
  { label: 'Europe/Rome', offset: 3600000, value: 'Europe/Rome' },
  { label: 'Europe/Samara', offset: 14400000, value: 'Europe/Samara' },
  { label: 'Europe/San_Marino', offset: 3600000, value: 'Europe/San_Marino' },
  { label: 'Europe/Sarajevo', offset: 3600000, value: 'Europe/Sarajevo' },
  { label: 'Europe/Saratov', offset: 14400000, value: 'Europe/Saratov' },
  { label: 'Europe/Simferopol', offset: 10800000, value: 'Europe/Simferopol' },
  { label: 'Europe/Skopje', offset: 3600000, value: 'Europe/Skopje' },
  { label: 'Europe/Sofia', offset: 10800000, value: 'Europe/Sofia' },
  { label: 'Europe/Stockholm', offset: 3600000, value: 'Europe/Stockholm' },
  { label: 'Europe/Tallinn', offset: 10800000, value: 'Europe/Tallinn' },
  { label: 'Europe/Tirane', offset: 3600000, value: 'Europe/Tirane' },
  { label: 'Europe/Tiraspol', offset: 10800000, value: 'Europe/Tiraspol' },
  { label: 'Europe/Ulyanovsk', offset: 14400000, value: 'Europe/Ulyanovsk' },
  { label: 'Europe/Uzhgorod', offset: 10800000, value: 'Europe/Uzhgorod' },
  { label: 'Europe/Vaduz', offset: 3600000, value: 'Europe/Vaduz' },
  { label: 'Europe/Vatican', offset: 3600000, value: 'Europe/Vatican' },
  { label: 'Europe/Vienna', offset: 3600000, value: 'Europe/Vienna' },
  { label: 'Europe/Vilnius', offset: 10800000, value: 'Europe/Vilnius' },
  { label: 'Europe/Volgograd', offset: 10800000, value: 'Europe/Volgograd' },
  { label: 'Europe/Warsaw', offset: 3600000, value: 'Europe/Warsaw' },
  { label: 'Europe/Zagreb', offset: 3600000, value: 'Europe/Zagreb' },
  { label: 'Europe/Zaporozhye', offset: 10800000, value: 'Europe/Zaporozhye' },
  { label: 'Europe/Zurich', offset: 3600000, value: 'Europe/Zurich' },
  { label: 'GB', offset: 0, value: 'GB' },
  { label: 'GB-Eire', offset: 0, value: 'GB-Eire' },
  { label: 'GMT', offset: 0, value: 'GMT' },
  { label: 'GMT-0', offset: 0, value: 'GMT-0' },
  { label: 'GMT+0', offset: 0, value: 'GMT+0' },
  { label: 'GMT0', offset: 0, value: 'GMT0' },
  { label: 'Greenwich', offset: 0, value: 'Greenwich' },
  { label: 'Hongkong', offset: 28800000, value: 'Hongkong' },
  { label: 'HST', offset: -36000000, value: 'HST' },
  { label: 'Iceland', offset: 0, value: 'Iceland' },
  {
    label: 'Indian/Antananarivo',
    offset: 10800000,
    value: 'Indian/Antananarivo',
  },
  { label: 'Indian/Chagos', offset: 21600000, value: 'Indian/Chagos' },
  { label: 'Indian/Christmas', offset: 25200000, value: 'Indian/Christmas' },
  { label: 'Indian/Cocos', offset: 23400000, value: 'Indian/Cocos' },
  { label: 'Indian/Comoro', offset: 10800000, value: 'Indian/Comoro' },
  { label: 'Indian/Kerguelen', offset: 18000000, value: 'Indian/Kerguelen' },
  { label: 'Indian/Mahe', offset: 14400000, value: 'Indian/Mahe' },
  { label: 'Indian/Maldives', offset: 18000000, value: 'Indian/Maldives' },
  { label: 'Indian/Mauritius', offset: 14400000, value: 'Indian/Mauritius' },
  { label: 'Indian/Mayotte', offset: 10800000, value: 'Indian/Mayotte' },
  { label: 'Indian/Reunion', offset: 14400000, value: 'Indian/Reunion' },
  { label: 'Iran', offset: 16200000, value: 'Iran' },
  { label: 'Israel', offset: 10800000, value: 'Israel' },
  { label: 'Jamaica', offset: -18000000, value: 'Jamaica' },
  { label: 'Japan', offset: 32400000, value: 'Japan' },
  { label: 'Kwajalein', offset: 43200000, value: 'Kwajalein' },
  { label: 'Libya', offset: 7200000, value: 'Libya' },
  { label: 'MET', offset: 3600000, value: 'MET' },
  { label: 'Mexico/BajaNorte', offset: -28800000, value: 'Mexico/BajaNorte' },
  { label: 'Mexico/BajaSur', offset: -25200000, value: 'Mexico/BajaSur' },
  { label: 'Mexico/General', offset: -21600000, value: 'Mexico/General' },
  { label: 'MST', offset: -25200000, value: 'MST' },
  { label: 'MST7MDT', offset: -25200000, value: 'MST7MDT' },
  { label: 'Navajo', offset: -25200000, value: 'Navajo' },
  { label: 'NZ', offset: 43200000, value: 'NZ' },
  { label: 'NZ-CHAT', offset: 45900000, value: 'NZ-CHAT' },
  { label: 'Pacific/Apia', offset: 50400000, value: 'Pacific/Apia' },
  { label: 'Pacific/Auckland', offset: 46800000, value: 'Pacific/Auckland' },
  {
    label: 'Pacific/Bougainville',
    offset: 39600000,
    value: 'Pacific/Bougainville',
  },
  { label: 'Pacific/Chatham', offset: 49500000, value: 'Pacific/Chatham' },
  { label: 'Pacific/Chuuk', offset: 36000000, value: 'Pacific/Chuuk' },
  { label: 'Pacific/Easter', offset: -18000000, value: 'Pacific/Easter' },
  { label: 'Pacific/Efate', offset: 39600000, value: 'Pacific/Efate' },
  { label: 'Pacific/Enderbury', offset: 46800000, value: 'Pacific/Enderbury' },
  { label: 'Pacific/Fakaofo', offset: 46800000, value: 'Pacific/Fakaofo' },
  { label: 'Pacific/Fiji', offset: 46800000, value: 'Pacific/Fiji' },
  { label: 'Pacific/Funafuti', offset: 43200000, value: 'Pacific/Funafuti' },
  { label: 'Pacific/Galapagos', offset: -21600000, value: 'Pacific/Galapagos' },
  { label: 'Pacific/Gambier', offset: -32400000, value: 'Pacific/Gambier' },
  {
    label: 'Pacific/Guadalcanal',
    offset: 39600000,
    value: 'Pacific/Guadalcanal',
  },
  { label: 'Pacific/Guam', offset: 36000000, value: 'Pacific/Guam' },
  { label: 'Pacific/Honolulu', offset: -36000000, value: 'Pacific/Honolulu' },
  { label: 'Pacific/Johnston', offset: -36000000, value: 'Pacific/Johnston' },
  { label: 'Pacific/Kanton', offset: 43200000, value: 'Pacific/Kanton' },
  {
    label: 'Pacific/Kiritimati',
    offset: 50400000,
    value: 'Pacific/Kiritimati',
  },
  { label: 'Pacific/Kosrae', offset: 39600000, value: 'Pacific/Kosrae' },
  { label: 'Pacific/Kwajalein', offset: 43200000, value: 'Pacific/Kwajalein' },
  { label: 'Pacific/Majuro', offset: 43200000, value: 'Pacific/Majuro' },
  { label: 'Pacific/Marquesas', offset: -34200000, value: 'Pacific/Marquesas' },
  { label: 'Pacific/Midway', offset: -39600000, value: 'Pacific/Midway' },
  { label: 'Pacific/Nauru', offset: 43200000, value: 'Pacific/Nauru' },
  { label: 'Pacific/Niue', offset: 43200000, value: 'Pacific/Niue' },
  { label: 'Pacific/Norfolk', offset: 41400000, value: 'Pacific/Norfolk' },
  { label: 'Pacific/Noumea', offset: 39600000, value: 'Pacific/Noumea' },
  { label: 'Pacific/Pago_Pago', offset: -39600000, value: 'Pacific/Pago_Pago' },
  { label: 'Pacific/Palau', offset: 32400000, value: 'Pacific/Palau' },
  { label: 'Pacific/Pitcairn', offset: -28800000, value: 'Pacific/Pitcairn' },
  { label: 'Pacific/Pohnpei', offset: 39600000, value: 'Pacific/Pohnpei' },
  { label: 'Pacific/Ponape', offset: 39600000, value: 'Pacific/Ponape' },
  {
    label: 'Pacific/Port_Moresby',
    offset: 36000000,
    value: 'Pacific/Port_Moresby',
  },
  { label: 'Pacific/Rarotonga', offset: -36000000, value: 'Pacific/Rarotonga' },
  { label: 'Pacific/Saipan', offset: 36000000, value: 'Pacific/Saipan' },
  { label: 'Pacific/Samoa', offset: -39600000, value: 'Pacific/Samoa' },
  { label: 'Pacific/Tahiti', offset: -36000000, value: 'Pacific/Tahiti' },
  { label: 'Pacific/Tarawa', offset: 43200000, value: 'Pacific/Tarawa' },
  { label: 'Pacific/Tongatapu', offset: 46800000, value: 'Pacific/Tongatapu' },
  { label: 'Pacific/Truk', offset: 36000000, value: 'Pacific/Truk' },
  { label: 'Pacific/Wake', offset: 43200000, value: 'Pacific/Wake' },
  { label: 'Pacific/Wallis', offset: 43200000, value: 'Pacific/Wallis' },
  { label: 'Pacific/Yap', offset: 36000000, value: 'Pacific/Yap' },
  { label: 'Poland', offset: 3600000, value: 'Poland' },
  { label: 'Portugal', offset: 0, value: 'Portugal' },
  { label: 'PRC', offset: 28800000, value: 'PRC' },
  { label: 'PST8PDT', offset: -28800000, value: 'PST8PDT' },
  { label: 'ROC', offset: 28800000, value: 'ROC' },
  { label: 'ROK', offset: 32400000, value: 'ROK' },
  { label: 'Singapore', offset: 28800000, value: 'Singapore' },
  { label: 'Turkey', offset: 10800000, value: 'Turkey' },
  { label: 'UCT', offset: 0, value: 'UCT' },
  { label: 'Universal', offset: 0, value: 'Universal' },
  { label: 'US/Alaska', offset: -32400000, value: 'US/Alaska' },
  { label: 'US/Aleutian', offset: -36000000, value: 'US/Aleutian' },
  { label: 'US/Arizona', offset: -25200000, value: 'US/Arizona' },
  { label: 'US/Central', offset: -18000000, value: 'US/Central' },
  { label: 'US/East-Indiana', offset: -14400000, value: 'US/East-Indiana' },
  { label: 'US/Eastern', offset: -14400000, value: 'US/Eastern' },
  { label: 'US/Hawaii', offset: -36000000, value: 'US/Hawaii' },
  { label: 'US/Indiana-Starke', offset: -18000000, value: 'US/Indiana-Starke' },
  { label: 'US/Michigan', offset: -14400000, value: 'US/Michigan' },
  { label: 'US/Mountain', offset: -21600000, value: 'US/Mountain' },
  { label: 'US/Pacific', offset: -25200000, value: 'US/Pacific' },
  { label: 'US/Samoa', offset: -39600000, value: 'US/Samoa' },
  { label: 'UTC', offset: 0, value: 'UTC' },
  { label: 'W-SU', offset: 10800000, value: 'W-SU' },
  { label: 'WET', offset: 0, value: 'WET' },
  { label: 'Zulu', offset: 0, value: 'Zulu' },
];
